trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'cloudaura-app-sc'
  acrRegistry: 'cloudaura.azurecr.io'
  tag: 'v1.0.$(Build.BuildId)'

steps:
  - checkout: self

  - task: AzureCLI@2
    displayName: 'Login, Build and Push Services'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logging into Azure Container Registry..."
        az acr login --name cloudaura

        services=("shop-order-api/auth-service" "shop-order-api/product-service" "shop-order-api/order-service" "shop-order-api/notif-service" "frontend")
        repos=("auth-service" "product-service" "order-service" "notif-service" "frontend")

        for i in "${!services[@]}"; do
          folder="${services[$i]}"
          repo="${repos[$i]}"
          
          echo "Building $repo from $folder..."
          cd "$folder"
          docker build -t $(acrRegistry)/$repo:$(tag) .
          
          echo "Pushing $repo to ACR..."
          docker push $(acrRegistry)/$repo:$(tag)
          cd - > /dev/null
        done
        
        echo "All services built and pushed successfully!"
